FinalCrimeSet<-read.csv(file.choose(),header=T,sep=",")
attach(FinalCrimeSet)
detach(FinalCrimeSet)
hist(TotalCrime,xlab = "Total Crime per 100K population")
mean(TotalCrime)
median(TotalCrime)
sd(TotalCrime)
min(TotalCrime)
max(TotalCrime)
plot(PctPopUnderPov,TotalCrime,type = 'p')
plot(PctPopUnderPov,TotalCrime,type = 'p')

mean(PctImmig)
median(PctImmig)
sd(PctImmig)
min(PctImmig)
max(PctImmig)
